### ISSUE TITLE
Unable to read 2D output of 3D fields

### ISSUE THREAD

**Issue by timothyas** [xgcm/xmitgcm#140]
Currently `open_mdsdataset` fails when any files which include 2D diagnostics of 3D fields. As an example, the following specification in `data.diagnostics` generates vertically integrated fields:

```
frequency(14) = 2635200.0,
   fields(1:8,14) = 'DFxE_TH ','DFyE_TH ','ADVx_TH ','ADVy_TH ',
                 'DFxE_SLT','DFyE_SLT','ADVx_SLT','ADVy_SLT',
   filename(14) = 'diags/trsp_2d_set1',
#vertically integrate fields we only use to compute vertically integr.
#meridional transports (also omit vertical transports, both to save space)
   fileFlags(14) = ' I      ',
```

However xmitgcm hiccups with this because available_diagnostics.log tells us that these fields, e.g. DFxE_TH, should be 3D but the meta information says they're 2D. 

Hard to think of how to incorporate this because this does not show up in the output meta information via the MITgcm, which I think would be the best solution. Perhaps this could be done by adding the fileFlags field to *.meta whenever it is provided to the diagnostics package. 

So maybe it's not an issue you / we want to fix through xmitgcm (especially because these files could just be read with the low level function `read_3d_llc_data`). Maybe we could add another optional input to open_mdsdataset to handle such conflict, but this might get pretty convoluted...

**Comment by ifenty** [comment]
@raphaeldussin  @rabernat  @timothyas 

We’ve been trying to integrate xmitgcm with our ecco_v4_py package including making tutorials to demonstrate its use for our upcoming ECCO summer school.  We ran into a problem yesterday when trying to load mitgcm data/meta file pairs created using the diagnostics package when the fields are 2D slices of ‘normally’ 3D fields.  For example, if we ask open_mdsdataset to open a data/meta file that contains a 2D slice of THETA (SST) then we get the error
 
  File "/home/ifenty/anaconda2/lib/python2.7/site-packages/xmitgcm/mds_store.py", line 864, in _reshape_for_llc
    assert data.ndim==len(dims)
 
I carefully traced this error back and found that in  load_from_prefix the metadata associated with the variable name is interrogated and contains a field called ‘dims’ which contains, in the case of THETA for example, metadata[‘dims’]=['k', 'j', 'i'].  Later, in _reshape_for_llc there is a check on the array dimension which fails because it expects 4 dimensions (face, k, j, i) while the 2D slice of THETA only contains 3 (face, j, i).    
 
I was able to make a very unsatisfactory hack which tosses the first (vertical) dimension in load_from_prefix under specific circumstances.  The hack, see below, throws out the first (depth dimension) of the dims list when the dims list has 3 elements and the array has 3 dimensions and one of the dimension names is not ‘face’.  In other words, when the field array has size (13, 90, 90) and the dim list has (k*, j, i) then the ‘k*’ dimension is tossed so that when ‘face’ is added to the dimension list, the _reshape_for_llc_ does not throw an error. 
 
Please help provide a quick fix to this problem in xmitgcm so that we can highlight the use of xmitgcm in the summer school for the loading of 2D slices of normally 3D llc fields.  Summer school starts in about one week.  
 
Feel free to use my hack or something more intelligent.  One perhaps more robust option is to read the .meta file after loading the .data file to get the expected dimensions of the variables.  Once one has the expected dimensions from the .meta file, one can toss the depth dimension from the variable’s ‘dims’ list if the .meta says the file has 2D fields and the variable’s ‘dims’ list contains ‘k’, ‘k_l’, ‘k_u’.  I hope that make sense.
 
 
 
 
 
 
Code snippet from my hacked solution
 
mds_store.py / load_from_prefix.
 
 
           # Some 2D output squeezes one of the dimensions out (e.g. hFacC).
            # How should we handle this? Can either eliminate one of the dims
            # or add an extra axis to the data. Let's try the former, on the
            # grounds that it is simpler for the user.
            if len(dims) == 3 and data.ndim == 2:
                # Deleting the first dimension (z) assumes that 2D data always
                # corresponds to x,y horizontal data. Is this really true?
                # The answer appears to be yes: 2D (x|y,z) data retains the
                # missing dimension as an axis of length 1.
                dims = dims[1:]
            elif len(dims) == 1 and (data.ndim == 2 or data.ndim == 3):
                # this is for certain profile data like RC, PHrefC, etc.
                # for some reason, dask arrays don't work here
                # ok to promote to numpy array because data is always 1D
                data = np.atleast_1d(np.asarray(data).squeeze())
           
            if len(dims) == 3 and data.ndim == 3 and 'face' not in dims:
                print ('condition red')
                dims = dims[1:]
 
 
code which tests that data.ndim is the same as len(dim) which has had ‘face’ added to the dimension list before ‘j’, or ‘j_g’.
 
def _reshape_for_llc(dims, data):
    """Take dims and data and return modified / reshaped dims and data for
    llc geometry."""
 
    # the data should already come shaped correctly for llc
    # but the dims are not yet correct
 
    # the only dimensions that get expanded into faces
    expand_dims = ['j', 'j_g']
    for dim in expand_dims:
        if dim in dims:
            # add face dimension to dims
            jdim = dims.index(dim)
            dims.insert(jdim, LLC_FACE_DIMNAME)
           
            print (data.ndim, dims, len(dims))
           
            assert data.ndim==len(dims)
    return dims, data

**Comment by raphaeldussin** [comment]
@ifenty @timothyas can you put an example pair (data/meta) on dropbox or similar so I can test?

**Comment by ifenty** [comment]
@raphaeldussin @timothyas 

**data/meta files are here:**
https://www.dropbox.com/sh/m1zn58p20aab9m7/AADiKpiQW89twS5w92wDJMZVa?dl=0

they contain 2D slices of theta and salt (surface fields in fact)
```
 nDims = [   2 ];
 dimList = [
    90,    1,   90,
  1170,    1, 1170
 ];
 dataprec = [ 'float32' ];
 nrecords = [     2 ];
 timeStepNumber = [        732 ];
 timeInterval = [  2.548800000000E+06  2.635200000000E+06 ];
 missingValue = [ -9.99000000000000E+02 ];
 nFlds = [    2 ];
 fldList = {
 'THETA   ' 'SALT    '
 };
```


**original command that fails:**
``xm.open_mdsdataset(data_dir, grid_dir=grid_dir, iters=732, read_grid=True, prefix='state_daily_2d_set3', grid_vars_to_coords=True, geometry='llc')``


I included my hacked mds_store.py in the dropbox folder which removes 'k' from the variable's list of dims under the problematic conditions in question.

Let me know if you have trouble accessing the dropbox files.

**Comment by rabernat** [comment]
The fundamental challenge I see here is that the `.meta` file does not include the information needed to figure out _which_ k level the field contains. There could be one single k level or multiple. In an ideal world, we could somehow infer or specify this information and use it to populate the k-values of these fields. But as far as I know, the only place it is actually present is in `data.diagnostics`.

I am fine with using @ifenty's solution to overcome the specific case where the diagnostic is a 2D slice of a 3D field. One thing I worry about is broadcasting--what if I have a 2D slice at 1000 m depth? If we just strip the k dimension from the data, we are allowed to broadcast it against a surface 2D field, potentially getting a wrong result.

For reference, the original lines in question are here:
https://github.com/xgcm/xmitgcm/blob/79fafbdd0cc09da29e68c89f88cbb7e13c46ca31/xmitgcm/mds_store.py#L659-L673

**Comment by rabernat** [comment]
@ifenty - would you feel comfortable opening up a pull request with the proposed change? I think that would be the best path forward. Here are the full instructions for how to do it: https://xmitgcm.readthedocs.io/en/latest/development.html#develpment-workflow

**Comment by rabernat** [comment]
I want to make sure this doesn't slip. If we are going to get this fixed in time for the summer school, we need to get a PR started asap, merge it, and then release 0.2.3.

Who is going to make the PR?

**Comment by raphaeldussin** [comment]
I'm on it

**Comment by ifenty** [comment]
@rabernat @raphaeldussin thank you guys for moving on this.

**Comment by ifenty** [comment]
@rabernat 

_The fundamental challenge I see here is that the .meta file does not include the information needed to figure out which k level the field contains. There could be one single k level or multiple. In an ideal world, we could somehow infer or specify this information and use it to populate the k-values of these fields. But as far as I know, the only place it is actually present is in data.diagnostics._

Exactly.  Diags also allows vertical integrals so there may not even be single k value.  We can advocate for increasing the information provided in the .meta files eventually.  Alternatively, an interim solution would be to allow the user to provide their own 'meta' information for variable.    The meta information provided by the user would replace those fields read from available_diagnostics.  This could be done in the form of a dictionary of dictionaries, with keys for variable names subkeys for the variable-specific metadata.  

Maybe in the short term you can just add a 'vertical levels' list argument.  If len(vert_levels) != the number expected from looking at available_diagnostics then use that number instead.  The user-specified vertical levels can be used to preserve broadcasting functionality.
