### ISSUE TITLE
The volume weighted averaging should use ds.drF instead of ds.drC

### ISSUE THREAD

**Issue by ifenty** [xgcm/xmitgcm#64]
The volume weighted averaging should use ds.drF instead of ds.drC
Ian
 
 
Volume Weighting
However, it is still not properly volume weighted. To take a volume-weighted average, you can do:
volume = ds.hFacC * ds.drC * ds.rA
(ds.S * volume).sum() / volume.sum()
>>> <xarray.DataArray ()>
array(34.779126627139945)
This represents the correct mean ocean salinity. A different land mask and volume weighting is required for variables located at the u and v points.

**Comment by rabernat** [comment]
Thanks for this Ian!

Would you be comfortable putting together a pull-request to fix this?

Since it's just a doc edit, it can all be done from within github. Just go to the page:
https://github.com/xgcm/xmitgcm/blob/master/doc/examples.rst
click the "edit" pencil icon in the upper right corner, make the changes, and then select "Create a new branch for this commit and start a pull request".

**Comment by ifenty** [comment]
Done, that was easy.

 

I’m trying to figure out how make web pages using sphinx/github for my new ECCOv4 routines and tutorial examples.

 

I see that some people host their sphinx-generated docs on github (github pages) while I see you are using readthedocs.  What are the pros and cons?  Why are you using readthedocs?

 

Also, can you point me to some simple tutorial or instructions for getting started with sphinx?  I am attracted to the idea of having some documentation pages auto generated from my py modules.  Can you describe your workflow for generating/updating the docs?

 

 

Ian

 

 

On 1/16/18, 12:26 PM, "Ryan Abernathey" <notifications@github.com> wrote:

 

Thanks for this Ian!

Would you be comfortable putting together a pull-request to fix this?

Since it's just a doc edit, it can all be done from within github. Just go to the page:
https://github.com/xgcm/xmitgcm/blob/master/doc/examples.rst
click the "edit" pencil icon in the upper right corner, make the changes, and then select "Create a new branch for this commit and start a pull request".

**Comment by rabernat** [comment]
It can't quite be done, because I don't see your pull request on this repository
https://github.com/xgcm/xmitgcm/pulls

**Comment by rabernat** [comment]
> I see that some people host their sphinx-generated docs on github (github pages) while I see you are using readthedocs.  What are the pros and cons?  Why are you using readthedocs?

I use readthedocs because it automatically builds the documentation for each release in a controlled environment. Hosting sphinx-generated docs on github pages is a more manual process and can't accommodate multiple versions.

**Comment by rabernat** [comment]
> Also, can you point me to some simple tutorial or instructions for getting started with sphinx?  I am attracted to the idea of having some documentation pages auto generated from my py modules.  Can you describe your workflow for generating/updating the docs?

The sphinx [getting started guide](http://www.sphinx-doc.org/en/stable/tutorial.html) is probably a good place to start. For more advanced stuff, I think most of us just learned this by copying an existing project and modifying it to suit our needs.

The main thing you have to decide is whether you want to actually *run* the example code when you generate your documentation. This is more robust and less error-prone. But it takes more work up front to set up the environment.

I think notebooks are the ideal environment to write such documentation, because you can easily combine text, code and figures. The [`nbsphinx`](https://nbsphinx.readthedocs.io/en/0.2.14/index.html) extension makes it easy to include notebooks in sphinx sites.

Here is where it is configured for xgcm's readthedocs build:
https://github.com/xgcm/xgcm/blob/master/doc/conf.py#L43-L48
